### ISSUE TITLE
2.1.6

### ISSUE THREAD

**Issue by aeskimo** [nicoh88/homebridge-vorwerk#9]
New Firmware doesn't work

**Comment by Kohle81** [comment]
Hello @aeskimo 
I think if you ask the developer for help, it takes more than a short thankless remark.  The developer does this voluntarily and I no longer have the Vorwerk at all. Thanks anyway for pointing out that the latest firmware no longer works.  Maybe you would like to give more information and kindly ask and ask the developer again?  Greetings Manuel

**Comment by sebastianlohmann** [comment]
Same for me - I'm running a VR200 with firmware 2.1.6 (it worked with 2.1.4 before). Home bridge protocol says:

`[VorwerkVacuumRobot] Could not find robot_serial for specified vendor_name: [object Object]`

Nothing happens when I push any of the buttons (of the home app). Also the dock status is not reported anymore.

It'd be great if you could fix that - :-).

**Comment by nicoh88** [comment]
#11
